package com.example.cityflowbkk.features.stationmapping.repository

import com.example.cityflowbkk.features.stationmapping.model.BtsStation
import com.example.cityflowbkk.features.stationmapping.model.StationLine

/**
 * Static list of every station visible on the BTS/MRT network map image.
 * Station IDs follow standard official codes where available.
 */
object BtsStationRepository {

    val allStations: List<BtsStation> = buildList {
        // ── Sukhumvit Line (N/E extensions) ──────────────────────────────────
        add(BtsStation("N24", "Khu Khot", StationLine.SUKHUMVIT))
        add(BtsStation("N23", "Yaek Kor Por Aor", StationLine.SUKHUMVIT))
        add(BtsStation("N22", "Royal Thai Air Force Museum", StationLine.SUKHUMVIT))
        add(BtsStation("N21", "Bhumibhol Adulyadej Hospital", StationLine.SUKHUMVIT))
        add(BtsStation("N20", "Sai Mai", StationLine.SUKHUMVIT))
        add(BtsStation("N19", "Phahon Yothin 59", StationLine.SUKHUMVIT))
        add(BtsStation("N18", "Phahon Yothin 57", StationLine.SUKHUMVIT))
        add(BtsStation("N17", "Watcharaphon", StationLine.SUKHUMVIT))
        add(BtsStation("N16", "Royal Forest Department", StationLine.SUKHUMVIT))
        add(BtsStation("N15", "Kasetsart University", StationLine.SUKHUMVIT))
        add(BtsStation("N14", "Sena Nikhom", StationLine.SUKHUMVIT))
        add(BtsStation("N13", "Ratchayothin", StationLine.SUKHUMVIT))
        add(BtsStation("N12", "Phahon Yothin 24", StationLine.SUKHUMVIT))
        add(BtsStation("N11", "Ha Yaek Lat Phrao", StationLine.SUKHUMVIT))
        add(BtsStation("N10", "Mo Chit", StationLine.SUKHUMVIT))
        add(BtsStation("N9", "Saphan Khwai", StationLine.SUKHUMVIT))
        add(BtsStation("N8", "Sena Ruam", StationLine.SUKHUMVIT))
        add(BtsStation("N7", "Ari", StationLine.SUKHUMVIT))
        add(BtsStation("N6", "Sanam Pao", StationLine.SUKHUMVIT))
        add(BtsStation("N5", "Victory Monument", StationLine.SUKHUMVIT))
        add(BtsStation("N4", "Phaya Thai", StationLine.SUKHUMVIT))
        add(BtsStation("N3", "Ratchathewi", StationLine.SUKHUMVIT))
        add(BtsStation("CEN", "Siam", StationLine.SUKHUMVIT))
        add(BtsStation("E1", "Chit Lom", StationLine.SUKHUMVIT))
        add(BtsStation("E2", "Phloen Chit", StationLine.SUKHUMVIT))
        add(BtsStation("E3", "Nana", StationLine.SUKHUMVIT))
        add(BtsStation("E4", "Asok", StationLine.SUKHUMVIT))
        add(BtsStation("E5", "Phrom Phong", StationLine.SUKHUMVIT))
        add(BtsStation("E6", "Thong Lo", StationLine.SUKHUMVIT))
        add(BtsStation("E7", "Ekkamai", StationLine.SUKHUMVIT))
        add(BtsStation("E8", "Phra Khanong", StationLine.SUKHUMVIT))
        add(BtsStation("E9", "On Nut", StationLine.SUKHUMVIT))
        add(BtsStation("E10", "Bang Chak", StationLine.SUKHUMVIT))
        add(BtsStation("E11", "Punnawithi", StationLine.SUKHUMVIT))
        add(BtsStation("E12", "Udom Suk", StationLine.SUKHUMVIT))
        add(BtsStation("E13", "Bang Na", StationLine.SUKHUMVIT))
        add(BtsStation("E14", "Bearing", StationLine.SUKHUMVIT))
        add(BtsStation("E15", "Samrong", StationLine.SUKHUMVIT))
        add(BtsStation("E16", "Pu Chao", StationLine.SUKHUMVIT))
        add(BtsStation("E17", "Chang Erawan", StationLine.SUKHUMVIT))
        add(BtsStation("E18", "Royal Thai Naval Academy", StationLine.SUKHUMVIT))
        add(BtsStation("E19", "Pak Nam", StationLine.SUKHUMVIT))
        add(BtsStation("E20", "Srinagarindra", StationLine.SUKHUMVIT))
        add(BtsStation("E21", "Phraek Sa", StationLine.SUKHUMVIT))
        add(BtsStation("E22", "Sai Luat", StationLine.SUKHUMVIT))
        add(BtsStation("E23", "Kheha", StationLine.SUKHUMVIT))

        // ── Silom Line ────────────────────────────────────────────────────────
        add(BtsStation("S1", "Ratchadamri", StationLine.SILOM))
        add(BtsStation("S2", "Sala Daeng", StationLine.SILOM))
        add(BtsStation("S3", "Chong Nonsi", StationLine.SILOM))
        add(BtsStation("S4", "Saint Louis", StationLine.SILOM))
        add(BtsStation("S5", "Surasak", StationLine.SILOM))
        add(BtsStation("S6", "Saphan Taksin", StationLine.SILOM))
        add(BtsStation("S7", "Krung Thon Buri", StationLine.SILOM))
        add(BtsStation("S8", "Wongwian Yai", StationLine.SILOM))
        add(BtsStation("S9", "Pho Nimit", StationLine.SILOM))
        add(BtsStation("S10", "Talat Phlu", StationLine.SILOM))
        add(BtsStation("S11", "Wutthakat", StationLine.SILOM))
        add(BtsStation("S12", "Bang Wa", StationLine.SILOM))

        // ── Gold Line ─────────────────────────────────────────────────────────
        add(BtsStation("G1", "Krung Thon Buri (Gold)", StationLine.GOLD))
        add(BtsStation("G2", "Charoen Nakhon", StationLine.GOLD))
        add(BtsStation("G3", "Khlong San", StationLine.GOLD))

        // ── Airport Rail Link ─────────────────────────────────────────────────
        add(BtsStation("A1", "Phaya Thai (ARL)", StationLine.AIRPORT_RAIL_LINK))
        add(BtsStation("A2", "Ratchaprarop", StationLine.AIRPORT_RAIL_LINK))
        add(BtsStation("A3", "Makkasan", StationLine.AIRPORT_RAIL_LINK))
        add(BtsStation("A4", "Ramkhamhaeng (ARL)", StationLine.AIRPORT_RAIL_LINK))
        add(BtsStation("A5", "Hua Mak", StationLine.AIRPORT_RAIL_LINK))
        add(BtsStation("A6", "Ban Thap Chang", StationLine.AIRPORT_RAIL_LINK))
        add(BtsStation("A7", "Lat Krabang", StationLine.AIRPORT_RAIL_LINK))
        add(BtsStation("A8", "Suvarnabhumi", StationLine.AIRPORT_RAIL_LINK))

        // ── MRT Blue Line ─────────────────────────────────────────────────────
        add(BtsStation("BL01", "Lak Song", StationLine.MRT_BLUE))
        add(BtsStation("BL02", "Phasi Charoen", StationLine.MRT_BLUE))
        add(BtsStation("BL03", "Bang Khae", StationLine.MRT_BLUE))
        add(BtsStation("BL04", "Nakhon Si", StationLine.MRT_BLUE))
        add(BtsStation("BL05", "Hua Lamphong", StationLine.MRT_BLUE))
        add(BtsStation("BL06", "Sam Yan", StationLine.MRT_BLUE))
        add(BtsStation("BL07", "Silom (MRT)", StationLine.MRT_BLUE))
        add(BtsStation("BL08", "Lumphini", StationLine.MRT_BLUE))
        add(BtsStation("BL09", "Khlong Toei", StationLine.MRT_BLUE))
        add(BtsStation("BL10", "Queen Sirikit National Convention Centre", StationLine.MRT_BLUE))
        add(BtsStation("BL11", "Sukhumvit (MRT)", StationLine.MRT_BLUE))
        add(BtsStation("BL12", "Phetchaburi", StationLine.MRT_BLUE))
        add(BtsStation("BL13", "Thailand Cultural Centre", StationLine.MRT_BLUE))
        add(BtsStation("BL14", "Huai Khwang", StationLine.MRT_BLUE))
        add(BtsStation("BL15", "Sutthisan", StationLine.MRT_BLUE))
        add(BtsStation("BL16", "Ratchadaphisek", StationLine.MRT_BLUE))
        add(BtsStation("BL17", "Lat Phrao (MRT)", StationLine.MRT_BLUE))
        add(BtsStation("BL18", "Phahon Yothin (MRT)", StationLine.MRT_BLUE))
        add(BtsStation("BL19", "Chatuchak Park", StationLine.MRT_BLUE))
        add(BtsStation("BL20", "Kamphaeng Phet", StationLine.MRT_BLUE))
        add(BtsStation("BL21", "Bang Sue", StationLine.MRT_BLUE))
        add(BtsStation("BL22", "Tao Poon", StationLine.MRT_BLUE))
        add(BtsStation("BL23", "Bang Pho", StationLine.MRT_BLUE))
        add(BtsStation("BL24", "Khlong Bang Phai", StationLine.MRT_BLUE))
        add(BtsStation("BL25", "Yaek Nonthaburi 1", StationLine.MRT_BLUE))
        add(BtsStation("BL26", "Nonthaburi Civic Centre", StationLine.MRT_BLUE))
        add(BtsStation("BL27", "Ministry of Public Health", StationLine.MRT_BLUE))
        add(BtsStation("BL28", "Sam Yaek Bang Yai", StationLine.MRT_BLUE))
        add(BtsStation("BL29", "Bang Yai Market", StationLine.MRT_BLUE))
        add(BtsStation("BL30", "Sai Ma", StationLine.MRT_BLUE))
        add(BtsStation("BL31", "Khlong Bang Phai (West)", StationLine.MRT_BLUE))
        add(BtsStation("BL32", "Phra Nang Klao Bridge", StationLine.MRT_BLUE))
        add(BtsStation("BL33", "Talad Bang Yai", StationLine.MRT_BLUE))
        add(BtsStation("BL34", "Khlong Bang Phai 2", StationLine.MRT_BLUE))
        add(BtsStation("BL35", "Bang Rak Noi Tha It", StationLine.MRT_BLUE))
        add(BtsStation("BL36", "Bang Krasor", StationLine.MRT_BLUE))
        add(BtsStation("BL37", "Saphan Phra Nang Klao", StationLine.MRT_BLUE))
        add(BtsStation("BL38", "Tha Phra", StationLine.MRT_BLUE))

        // ── MRT Purple Line ───────────────────────────────────────────────────
        add(BtsStation("PP01", "Tao Poon (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP02", "Bang Son", StationLine.MRT_PURPLE))
        add(BtsStation("PP03", "Wong Sawang", StationLine.MRT_PURPLE))
        add(BtsStation("PP04", "Khae Rai", StationLine.MRT_PURPLE))
        add(BtsStation("PP05", "Yaek Tiwanon", StationLine.MRT_PURPLE))
        add(BtsStation("PP06", "Nonthaburi 1", StationLine.MRT_PURPLE))
        add(BtsStation("PP07", "Bang Krasor (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP08", "Sai Ma (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP09", "Phra Nang Klao Bridge (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP10", "Saphan Phrabat", StationLine.MRT_PURPLE))
        add(BtsStation("PP11", "Bang Phlu", StationLine.MRT_PURPLE))
        add(BtsStation("PP12", "Talad Bang Yai (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP13", "Bang Yai Market (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP14", "Sam Yaek Bang Yai (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP15", "Khlong Bang Phai (Purple)", StationLine.MRT_PURPLE))
        add(BtsStation("PP16", "Bang Rak Noi (Purple)", StationLine.MRT_PURPLE))

        // ── MRT Yellow Line ───────────────────────────────────────────────────
        add(BtsStation("YL01", "Lat Phrao (Yellow)", StationLine.MRT_YELLOW))
        add(BtsStation("YL02", "Phawana", StationLine.MRT_YELLOW))
        add(BtsStation("YL03", "Chokchai 4", StationLine.MRT_YELLOW))
        add(BtsStation("YL04", "Lat Phrao 71", StationLine.MRT_YELLOW))
        add(BtsStation("YL05", "Lat Phrao 83", StationLine.MRT_YELLOW))
        add(BtsStation("YL06", "Mahat Thai", StationLine.MRT_YELLOW))
        add(BtsStation("YL07", "Lat Phrao 101", StationLine.MRT_YELLOW))
        add(BtsStation("YL08", "Bang Kapi", StationLine.MRT_YELLOW))
        add(BtsStation("YL09", "Yaek Lam Sali", StationLine.MRT_YELLOW))
        add(BtsStation("YL10", "Si Kritha", StationLine.MRT_YELLOW))
        add(BtsStation("YL11", "Hua Mak (Yellow)", StationLine.MRT_YELLOW))
        add(BtsStation("YL12", "Si Lasan", StationLine.MRT_YELLOW))
        add(BtsStation("YL13", "Si Bearing", StationLine.MRT_YELLOW))
        add(BtsStation("YL14", "Si Thepha", StationLine.MRT_YELLOW))
        add(BtsStation("YL15", "Thipphawan", StationLine.MRT_YELLOW))
        add(BtsStation("YL16", "Chaloem Phrakiat Ratchakan Thi 9", StationLine.MRT_YELLOW))
        add(BtsStation("YL17", "Phatthanakan", StationLine.MRT_YELLOW))
        add(BtsStation("YL18", "On Nut (Yellow)", StationLine.MRT_YELLOW))
        add(BtsStation("YL19", "Rama 9 (Yellow)", StationLine.MRT_YELLOW))
        add(BtsStation("YL20", "Samrong (Yellow)", StationLine.MRT_YELLOW))
        add(BtsStation("YL21", "Srinagarindra (Yellow)", StationLine.MRT_YELLOW))
        add(BtsStation("YL22", "Si Udom", StationLine.MRT_YELLOW))
        add(BtsStation("YL23", "Si Lam", StationLine.MRT_YELLOW))

        // ── MRT Pink Line ─────────────────────────────────────────────────────
        add(BtsStation("PK01", "Khae Rai (Pink)", StationLine.MRT_PINK))
        add(BtsStation("PK02", "Yaek Pak Kret 30", StationLine.MRT_PINK))
        add(BtsStation("PK03", "Pak Kret Bypass", StationLine.MRT_PINK))
        add(BtsStation("PK04", "Chaengwattana 14", StationLine.MRT_PINK))
        add(BtsStation("PK05", "Si Rat", StationLine.MRT_PINK))
        add(BtsStation("PK06", "Impact Muang Thong Thani", StationLine.MRT_PINK))
        add(BtsStation("PK07", "Muang Thong Thani", StationLine.MRT_PINK))
        add(BtsStation("PK08", "Royal Jubilee", StationLine.MRT_PINK))
        add(BtsStation("PK09", "Chaengwattana Government Complex", StationLine.MRT_PINK))
        add(BtsStation("PK10", "National Telecom", StationLine.MRT_PINK))
        add(BtsStation("PK11", "Lak Si", StationLine.MRT_PINK))
        add(BtsStation("PK12", "Phahon Yothin Intersection", StationLine.MRT_PINK))
        add(BtsStation("PK13", "11th Infantry Regiment", StationLine.MRT_PINK))
        add(BtsStation("PK14", "Lat Pla Khao", StationLine.MRT_PINK))
        add(BtsStation("PK15", "Khu Mueang 4", StationLine.MRT_PINK))
        add(BtsStation("PK16", "Khu Mueang 6", StationLine.MRT_PINK))
        add(BtsStation("PK17", "Khu Mueang 8", StationLine.MRT_PINK))
        add(BtsStation("PK18", "Watcharaphon (Pink)", StationLine.MRT_PINK))
        add(BtsStation("PK19", "Nawamin", StationLine.MRT_PINK))
        add(BtsStation("PK20", "Nawamin 56", StationLine.MRT_PINK))
        add(BtsStation("PK21", "Ramintra 34", StationLine.MRT_PINK))
        add(BtsStation("PK22", "Ramintra 40", StationLine.MRT_PINK))
        add(BtsStation("PK23", "Ramintra 53", StationLine.MRT_PINK))
        add(BtsStation("PK24", "Ram Inthra Ram Indra", StationLine.MRT_PINK))
        add(BtsStation("PK25", "Khu Mueang 9", StationLine.MRT_PINK))
        add(BtsStation("PK26", "Khu Mueang 13", StationLine.MRT_PINK))
        add(BtsStation("PK27", "Khu Mueang 19", StationLine.MRT_PINK))
        add(BtsStation("PK28", "Min Buri", StationLine.MRT_PINK))
        add(BtsStation("PK29", "Eastern Bus Terminal", StationLine.MRT_PINK))
        add(BtsStation("PK30", "Si Rat Market", StationLine.MRT_PINK))
    }

    fun getById(id: String): BtsStation? = allStations.firstOrNull { it.id == id }

    fun getByLine(line: StationLine): List<BtsStation> =
        allStations.filter { it.line == line }

    fun search(query: String): List<BtsStation> {
        if (query.isBlank()) return allStations
        val q = query.trim().lowercase()
        return allStations.filter { it.name.lowercase().contains(q) }
    }
}
